-- ── Supabase Tables and RLS Policies for AniPlay ──
-- Copy and paste this script into your Supabase SQL Editor and click "Run"!

-- 1. Create User Profiles Table
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for Profiles
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" 
  ON public.user_profiles FOR SELECT 
  TO public 
  USING (true);

CREATE POLICY "Allow individual insert/update to profiles" 
  ON public.user_profiles FOR ALL 
  TO authenticated 
  USING (auth.uid() = id) 
  WITH CHECK (auth.uid() = id);


-- 2. Create Watchlist Table (User Bookmarks and Episode Progress)
CREATE TABLE IF NOT EXISTS public.watchlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  anime_id TEXT NOT NULL,
  status TEXT DEFAULT 'watching'::text,
  favorite BOOLEAN DEFAULT false,
  progress JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for Watchlist
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;

-- Watchlist Policies
CREATE POLICY "Allow users to manage their own watchlist" 
  ON public.watchlist FOR ALL 
  TO authenticated 
  USING (auth.uid() = user_id) 
  WITH CHECK (auth.uid() = user_id);

-- Create Watchlist Indexes for performance
CREATE INDEX IF NOT EXISTS idx_watchlist_user_anime ON public.watchlist(user_id, anime_id);


-- 3. Create Episode Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anime_id TEXT NOT NULL,
  episode INTEGER NOT NULL,
  username TEXT NOT NULL,
  content TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for Comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Comments Policies
CREATE POLICY "Allow public read access to comments" 
  ON public.comments FOR SELECT 
  TO public 
  USING (true);

CREATE POLICY "Allow authenticated users to insert comments" 
  ON public.comments FOR INSERT 
  TO public -- Allows posting comments (user_id will link if logged in, or null if guest)
  WITH CHECK (true);

-- Create Comments Indexes for fast loading
CREATE INDEX IF NOT EXISTS idx_comments_anime_episode ON public.comments(anime_id, episode);
